# schemas.py
# 📦 Purpose: Define request and response data structures using Pydantic

from pydantic import BaseModel, EmailStr

# 🔹 Used when client sends data to create a new user
# Note id is not included here because it's auto-generated by the DB

class UserCreate(BaseModel):
    name: str
    email: EmailStr
    age: int

# 🔹 Used when sending user data back to the client
class UserResponse(BaseModel):
    id: int
    name: str
    email: EmailStr
    age: int

    # Tells FastAPI to convert DB model → response model
    class Config:
        orm_mode = True
